//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.AuthenticationRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Authentication Web ServiceSoap", Namespace="http://webportalbridge.ptassoc.com/Authentication/", ConfigurationName="AuthenticationRef.AuthenticationWebServiceSoap")]
    public interface AuthenticationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name securityPassword from namespace http://webportalbridge.ptassoc.com/Authentication/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/Login", ReplyAction="*")]
        ServiceTest.AuthenticationRef.LoginResponse Login(ServiceTest.AuthenticationRef.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.LoginResponse> LoginAsync(ServiceTest.AuthenticationRef.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name securityPassword from namespace http://webportalbridge.ptassoc.com/Authentication/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateUser", ReplyAction="*")]
        ServiceTest.AuthenticationRef.AuthenticateUserResponse AuthenticateUser(ServiceTest.AuthenticationRef.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.AuthenticateUserResponse> AuthenticateUserAsync(ServiceTest.AuthenticationRef.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name securityPassword from namespace http://webportalbridge.ptassoc.com/Authentication/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateToken", ReplyAction="*")]
        ServiceTest.AuthenticationRef.AuthenticateTokenResponse AuthenticateToken(ServiceTest.AuthenticationRef.AuthenticateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/AuthenticateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.AuthenticateTokenResponse> AuthenticateTokenAsync(ServiceTest.AuthenticationRef.AuthenticateTokenRequest request);
        
        // CODEGEN: Generating message contract since element name securityPassword from namespace http://webportalbridge.ptassoc.com/Authentication/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/DeleteUserSession", ReplyAction="*")]
        ServiceTest.AuthenticationRef.DeleteUserSessionResponse DeleteUserSession(ServiceTest.AuthenticationRef.DeleteUserSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webportalbridge.ptassoc.com/Authentication/DeleteUserSession", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.DeleteUserSessionResponse> DeleteUserSessionAsync(ServiceTest.AuthenticationRef.DeleteUserSessionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ServiceTest.AuthenticationRef.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string securityPassword, string username, string password) {
            this.securityPassword = securityPassword;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ServiceTest.AuthenticationRef.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(ServiceTest.AuthenticationRef.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string securityPassword, string username, string password) {
            this.securityPassword = securityPassword;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(ServiceTest.AuthenticationRef.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateToken", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.AuthenticateTokenRequestBody Body;
        
        public AuthenticateTokenRequest() {
        }
        
        public AuthenticateTokenRequest(ServiceTest.AuthenticationRef.AuthenticateTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public AuthenticateTokenRequestBody() {
        }
        
        public AuthenticateTokenRequestBody(string securityPassword, string token) {
            this.securityPassword = securityPassword;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateTokenResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.AuthenticateTokenResponseBody Body;
        
        public AuthenticateTokenResponse() {
        }
        
        public AuthenticateTokenResponse(ServiceTest.AuthenticationRef.AuthenticateTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class AuthenticateTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateTokenResult;
        
        public AuthenticateTokenResponseBody() {
        }
        
        public AuthenticateTokenResponseBody(string AuthenticateTokenResult) {
            this.AuthenticateTokenResult = AuthenticateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserSessionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserSession", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.DeleteUserSessionRequestBody Body;
        
        public DeleteUserSessionRequest() {
        }
        
        public DeleteUserSessionRequest(ServiceTest.AuthenticationRef.DeleteUserSessionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class DeleteUserSessionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string securityPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public DeleteUserSessionRequestBody() {
        }
        
        public DeleteUserSessionRequestBody(string securityPassword, string token) {
            this.securityPassword = securityPassword;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserSessionResponse", Namespace="http://webportalbridge.ptassoc.com/Authentication/", Order=0)]
        public ServiceTest.AuthenticationRef.DeleteUserSessionResponseBody Body;
        
        public DeleteUserSessionResponse() {
        }
        
        public DeleteUserSessionResponse(ServiceTest.AuthenticationRef.DeleteUserSessionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webportalbridge.ptassoc.com/Authentication/")]
    public partial class DeleteUserSessionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteUserSessionResult;
        
        public DeleteUserSessionResponseBody() {
        }
        
        public DeleteUserSessionResponseBody(string DeleteUserSessionResult) {
            this.DeleteUserSessionResult = DeleteUserSessionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationWebServiceSoapChannel : ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap>, ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap {
        
        public AuthenticationWebServiceSoapClient() {
        }
        
        public AuthenticationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.AuthenticationRef.LoginResponse ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.Login(ServiceTest.AuthenticationRef.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string securityPassword, string username, string password) {
            ServiceTest.AuthenticationRef.LoginRequest inValue = new ServiceTest.AuthenticationRef.LoginRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.LoginRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            ServiceTest.AuthenticationRef.LoginResponse retVal = ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.LoginResponse> ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.LoginAsync(ServiceTest.AuthenticationRef.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.LoginResponse> LoginAsync(string securityPassword, string username, string password) {
            ServiceTest.AuthenticationRef.LoginRequest inValue = new ServiceTest.AuthenticationRef.LoginRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.LoginRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.AuthenticationRef.AuthenticateUserResponse ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.AuthenticateUser(ServiceTest.AuthenticationRef.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(string securityPassword, string username, string password) {
            ServiceTest.AuthenticationRef.AuthenticateUserRequest inValue = new ServiceTest.AuthenticationRef.AuthenticateUserRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.AuthenticateUserRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            ServiceTest.AuthenticationRef.AuthenticateUserResponse retVal = ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.AuthenticateUserResponse> ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.AuthenticateUserAsync(ServiceTest.AuthenticationRef.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.AuthenticateUserResponse> AuthenticateUserAsync(string securityPassword, string username, string password) {
            ServiceTest.AuthenticationRef.AuthenticateUserRequest inValue = new ServiceTest.AuthenticationRef.AuthenticateUserRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.AuthenticateUserRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.AuthenticationRef.AuthenticateTokenResponse ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.AuthenticateToken(ServiceTest.AuthenticationRef.AuthenticateTokenRequest request) {
            return base.Channel.AuthenticateToken(request);
        }
        
        public string AuthenticateToken(string securityPassword, string token) {
            ServiceTest.AuthenticationRef.AuthenticateTokenRequest inValue = new ServiceTest.AuthenticationRef.AuthenticateTokenRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.AuthenticateTokenRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.token = token;
            ServiceTest.AuthenticationRef.AuthenticateTokenResponse retVal = ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).AuthenticateToken(inValue);
            return retVal.Body.AuthenticateTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.AuthenticateTokenResponse> ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.AuthenticateTokenAsync(ServiceTest.AuthenticationRef.AuthenticateTokenRequest request) {
            return base.Channel.AuthenticateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.AuthenticateTokenResponse> AuthenticateTokenAsync(string securityPassword, string token) {
            ServiceTest.AuthenticationRef.AuthenticateTokenRequest inValue = new ServiceTest.AuthenticationRef.AuthenticateTokenRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.AuthenticateTokenRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.token = token;
            return ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).AuthenticateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.AuthenticationRef.DeleteUserSessionResponse ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.DeleteUserSession(ServiceTest.AuthenticationRef.DeleteUserSessionRequest request) {
            return base.Channel.DeleteUserSession(request);
        }
        
        public string DeleteUserSession(string securityPassword, string token) {
            ServiceTest.AuthenticationRef.DeleteUserSessionRequest inValue = new ServiceTest.AuthenticationRef.DeleteUserSessionRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.DeleteUserSessionRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.token = token;
            ServiceTest.AuthenticationRef.DeleteUserSessionResponse retVal = ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).DeleteUserSession(inValue);
            return retVal.Body.DeleteUserSessionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.DeleteUserSessionResponse> ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap.DeleteUserSessionAsync(ServiceTest.AuthenticationRef.DeleteUserSessionRequest request) {
            return base.Channel.DeleteUserSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.AuthenticationRef.DeleteUserSessionResponse> DeleteUserSessionAsync(string securityPassword, string token) {
            ServiceTest.AuthenticationRef.DeleteUserSessionRequest inValue = new ServiceTest.AuthenticationRef.DeleteUserSessionRequest();
            inValue.Body = new ServiceTest.AuthenticationRef.DeleteUserSessionRequestBody();
            inValue.Body.securityPassword = securityPassword;
            inValue.Body.token = token;
            return ((ServiceTest.AuthenticationRef.AuthenticationWebServiceSoap)(this)).DeleteUserSessionAsync(inValue);
        }
    }
}
